apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 5006      # Service inside Kubernetes
      targetPort: 5006  # Your FastAPI app port
      nodePort: 30006   # External access (change if needed)
  type: NodePort  # This makes it accessible outside Kubernetes
