apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 2  # Number of instances
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth:latest  # Make sure to push the correct Docker image
        ports:
        - containerPort: 5001
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@postgres-service:5432/authdb"
