apiVersion: v1
kind: Service
metadata:
  name: auth
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 5001      # Service inside Kubernetes
      targetPort: 5001  # Your FastAPI app port
      nodePort: 30001   # External access (change if needed)
  type: NodePort  # This makes it accessible outside Kubernetes
