apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: auth:latest  # Must match your local Docker image
        imagePullPolicy: Never  # Prevents Kubernetes from trying to pull from a registry
        ports:
        - containerPort: 5001
