apiVersion: apps/v1
kind: Deployment
metadata:
  name: liberary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liberary
  template:
    metadata:
      labels:
        app: liberary
    spec:
      containers:
      - name: liberary
        image: liberary:latest  # Must match your local Docker image
        imagePullPolicy: Never  # Prevents Kubernetes from trying to pull from a registry
        ports:
        - containerPort: 5004
