apiVersion: v1
kind: Service
metadata:
  name: library
spec:
  selector:
    app: library
  ports:
    - protocol: TCP
      port: 5004      # Service inside Kubernetes
      targetPort: 5004  # Your FastAPI app port
      nodePort: 30004   # External access (change if needed)
  type: NodePort  # This makes it accessible outside Kubernetes