apiVersion: v1
kind: Service
metadata:
  name: training
spec:
  selector:
    app: training
  ports:
    - protocol: TCP
      port: 5008      # Service inside Kubernetes
      targetPort: 5008  # Your FastAPI app port
      nodePort: 30008   # External access (change if needed)
  type: NodePort  # This makes it accessible outside Kubernetes
